- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      state: present
      autoclean: yes
      name:
      - vim
      - neovim
      - thunderbird
      - anki
      - borgbackup
      - calibre
      - emacs
      - enigmail
      - flatpak
      - ffmpeg
      - gimp
      - git-cola
      - golang
      - gpg
      - gpodder
      - hugo
      - imagemagick
      - inkscape
      - keepassxc
      - libreoffice
      - meld
      - obs-studio
      - postgresql
      - rbenv
      - remmina
      - simple-scan
      - seahorse
      - sqlite3
      - syncthing
      - libgtk-3-dev
      - python-vte
      - tilix
      - tmux
      - tor
      - transmission
      - vlc
      - wget
      - yubikey-personalization
  - name: Fix tilix dependency
    file:
      src: /etc/profile.d/vte-2.91.sh
      dest: /etc/profile.d/vte.sh
      owner: root
      group: root
      state: link

