- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    package:
      state: present
      name: "{{ item }}"
    loop:
      - anki
      - apt-transport-https
      - borgbackup
      - calibre
      - curl
      - emacs
      - ffmpeg
      - gimp
      - golang
      - gpodder
      - hugo
      - imagemagick
      - inkscape
      - libreoffice
      - meld
      - openssh-server
      - pandoc
      - remmina
      - simple-scan
      - seahorse
      - sqlite3
      - sshfs
      - thunderbird
      - vim
      - vlc
      - wget

  - name: Install encryption packages
    package:
      state: present
      name: "{{ item }}"
    loop:
      - gnupg2
      - gnupg-agent
      - dirmngr
      - cryptsetup
      - scdaemon
      - pcscd
      - secure-delete
      - hopenpgp-tools
      - yubikey-personalization

  - name: OpenVPN
    package:
      state: present
      name: "{{ item }}"
    loop:
      - openvpn
      - easy-rsa
      - network-manager-openvpn

  - name: Add Brave key by id from a keyserver
    apt_key:
      url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
      keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg
      state: present
  
  - name: Add Brave repository
    apt_repository:
      repo: deb https://brave-browser-apt-release.s3.brave.com {{ ansible_distribution_release }} main
      filename: brave-browser-release-{{ ansible_distribution_release }}.list
      state: present
      update_cache: yes

  - name: Install Brave
    apt:
      name: brave-browser
      state: present

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
