- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    package:
      state: present
      name: "{{ item }}"
    loop:
      - anki
      - apt-transport-https
      - borgbackup
      - calibre
      - curl
      - emacs
      - ffmpeg
      - gimp
      - golang
      - gpodder
      - hugo
      - imagemagick
      - inkscape
      - libreoffice
      - meld
      - openssh-server
      - pandoc
      - remmina
      - simple-scan
      - seahorse
      - sqlite3
      - sshfs
      - thunderbird
      - vim
      - vlc
      - wget

  - name: Install encryption packages
    package:
      state: present
      name: "{{ item }}"
    loop:
      - gnupg2
      - gnupg-agent
      - dirmngr
      - cryptsetup
      - scdaemon
      - pcscd
      - secure-delete
      - hopenpgp-tools
      - yubikey-personalization

  - name: OpenVPN
    package:
      state: present
      name: "{{ item }}"
    loop:
      - openvpn
      - easy-rsa
      - network-manager-openvpn

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
