- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - mc
      - tmux
      - calibre
      - anki
      - emacs
      - gpg
      - keepassxc
      - thunderbird
      - enigmail
      - libreoffice
      - slack
      - tor
      - vlc
      - obs-studio
      - gimp
      - imagemagick
      - meld
      - rbenv
