---

- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    package:
      state: present
      name: "{{ item }}"
    loop:
      - borgbackup
      - curl
      - flatpak
      - lsb
      - seahorse
      - sqlite3
      - syncthing
      - vim
      - wget
