---

- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      state: present
      autoclean: yes
      name:
      - borgbackup
      - curl
      - flatpak
      - lsb
      - seahorse
      - sqlite3
      - syncthing
      - vim
      - wget
  - name: Install GPG
    apt:
      state: present
      autoclean: yes
      name:
        - gnupg2
        - gnupg-agent
        - dirmngr
        - cryptsetup
        - scdaemon
        - pcscd
        - secure-delete
        - hopenpgp-tools
        - yubikey-personalization
  - name: OpenVPN
    apt:
      state: present
      autoclean: yes
      name:
        - openvpn
        - easy-rsa
        - network-manager-openvpn

