- hosts: localhost
  - name: Install development dependencies
    package:
      state: present
      name: "{{ item }}"
    loop:
      - build-essential
      - libssl-dev
      - libreadline-dev
      - libsqlite3-dev
      - sqlite3
      - libsqlite3-dev

  - name: Install rbenv
    git:
      repo: https://github.com/rbenv/rbenv.git
      dest: /home/skng/.rbenv

  - name: Install ruby-build
    git:
      repo: https://github.com/rbenv/ruby-build.git
      dest: /home/skng/.rbenv/plugins/ruby-build

  - name: Add VirtualBox repository
    apt_repository:
      repo: deb-src http://archive.canonical.com/ubuntu $(lsb_release -sc) contrib
      state: present
      update_cache: yes

  - name: Install VirtualBox
    apt:
      name: virtualbox
      state: present
      autoclean: yes

  - name: Install Docker
    apt:
      state: present
      autoclean: yes
      name:
      - docker
      - docker-compose

  - name: Add Vagrant
    become: TRUE
    apt:
      state: present
      deb: https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
